services:
  # Backend Spring Boot
  backend:
    build:
      context: ./source/backend/QuizExam_Student
      dockerfile: Dockerfile
    container_name: quizexam-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://103.229.42.113:3306/quiz
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: lht@39412990
      UPLOADS_SUBJECT: /app/uploads/img-subject
      UPLOADS_QUESTION: /app/uploads/img-question
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: classpath:/static/, file:/app/uploads/
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    networks:
      - quizexam-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Angular
  frontend:
    build:
      context: ./source/frontend/Angular_QuizExam
      dockerfile: Dockerfile
    container_name: quizexam-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - quizexam-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nginx Reverse Proxy (Optional - for production)
  nginx-proxy:
    image: nginx:alpine
    container_name: quizexam-proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - quizexam-network
    profiles:
      - production

volumes:
  backend_uploads:
    driver: local

networks:
  quizexam-network:
    driver: bridge
